version: "3.9"
services: 
    api:
        image: mehmet-yildiz/nestjs-dockerized
        build:
            dockerfile: Dockerfile
            context: .
        depends_on:
            - postgres
        environment:
            DATABASE_URL: postgres://user:password@postgres:5432/db
            NODE_ENV: development
            PORT: 3000
        ports:
          - "8080:3000"

    postgres:
      image: postgres:14.6
      ports: 
          - "35000:5432"
      environment: 
          POSTGRES_USER: user
          POSTGRES_PASSWORD: passwword
          POSTGRES_DB: db
